# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7612b8ab29ed1118850ff16c14b0e086720d273bdc571041f5143f1322d32964cd647100cc913f1f4b2c1e7319a4238f165cf4123adf92d8020005dd2299c462

test:
  secret_key_base: d1a9d1a0b31a67ab7d68c1b4e5e361060469a1335f5f39ff0d5aaee787b8b5f4380a0937cacad044e15fa41f501deac2f652b3820499d574a04364bf39533bb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
